// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"database/sql"
)

type User struct {
	ID             int64
	TgID           int64
	LangAutodetect bool
	RegisteredAt   sql.NullTime
}
